import express from 'express';
import * as abhaenrollController from '../controllers/access_token.js';
import * as loginmobileController from '../controllers/login_via_mobile.js';
import * as loginaadharController from '../controllers/login_via_aadhar.js';
import * as loginabhaController from '../controllers/login_via_abha.js';
import * as loginabhanumberController from '../controllers/login_via_abha_number.js';
import * as re_kycController from '../controllers/re_kyc.js';
import * as deactivateController from '../controllers/deactivate.js';
import * as deleteController from '../controllers/delete.js';
import * as reactivateController from '../controllers/reactivate.js';
import * as changePasswordController from '../controllers/change_password.js';
import * as forgotController from '../controllers/forgot.js';
import * as dlController from '../controllers/Dl_enroll.js';
import * as retrievalController from '../controllers/retrieval.js';
import * as emailController from '../controllers/email_verify.js';
import * as singleapiController from '../controllers/singleapi.js';

const router = express.Router();

router.post('/token', abhaenrollController.getAccessToken);


router.post('/enrollment/aadhar/send-otp', abhaenrollController.sendAadhaarOtp);
router.post('/enrollment/aadhar/verify-otp', abhaenrollController.verifyAadhaarOtp);
router.get('/profile', abhaenrollController.getProfileInfo);
router.post('/login/mobile/send-otp', loginmobileController.requestLoginOtp);
router.post('/login/mobile/verify-otp', loginmobileController.verifyLoginOtp);
router.post('/login/aadhar/send-otp', loginaadharController.requestLoginOtp);
router.post('/login/aadhar/verify-otp', loginaadharController.verifyLoginOtp);
router.post('/login/abha/send-otp', loginabhaController.requestLoginOtp);
router.post('/login/abha/verify-otp', loginabhaController.verifyLoginOtp);
router.post('/retrieval/send-otp', retrievalController.requestLoginOtp);
router.post('/retrieval/verify-otp', retrievalController.verifyLoginOtp);
router.get('/profile/qrcode', abhaenrollController.getQrCode);
router.post('/login/abha/number/send-otp', loginabhanumberController.requestLoginOtp);
router.post('/login/abha/number/verify-otp', loginabhanumberController.verifyLoginOtp);
router.post('/account/re-kyc/send-otp', re_kycController.requestLoginOtp);
router.post('/account/re-kyc/verify-otp', re_kycController.verifyLoginOtp);
router.post('/account/de-activate/send-otp', deactivateController.requestLoginOtp);
router.post('/account/de-activate/verify-otp', deactivateController.verifyLoginOtp);
router.post('/account/delete/send-otp', deleteController.requestLoginOtp);
router.post('/account/delete/verify-otp', deleteController.verifyLoginOtp);
router.post('/account/re-activate/send-otp', reactivateController.requestLoginOtp);
router.post('/account/re-activate/verify-otp', reactivateController.verifyLoginOtp);
router.post('/account/change-password/send-otp', changePasswordController.requestLoginOtp);
router.post('/account/change-password/verify-otp', changePasswordController.verifyLoginOtp);
router.get('/profile/logout', abhaenrollController.logout);
router.post('/forgot/mobile/send-otp', forgotController.requestMobileOtp);
router.post('/forgot/mobile/verify-otp', forgotController.verifyMobileOtp);
router.post('/forgot/aadhar/send-otp', forgotController.requestAadharOtp);
router.post('/forgot/aadhar/verify-otp', forgotController.verifyAadharOtp);
router.post('/dl/enroll/send-otp', dlController.sendDlOtp);
router.post('/dl/enroll/verify-otp', dlController.verifyDlOtp);
router.post('/dl/enroll/create-enroll-number', dlController.createENumber);
router.get('/profile/abha-card', abhaenrollController.getAbhaCard);
router.patch('/profile/photo', abhaenrollController.getphoto);
router.post('/account/verify', loginmobileController.verifyuser);
router.post('/update/email/send-otp', emailController.requestOtp);
router.post('/update/email/verify-otp', emailController.verifyOtp);
router.post('/update/mobile/send-otp', emailController.requestMobileOtp);
router.post('/update/mobile/verify-otp', emailController.verifyMobileOtp);
router.post('/profile/singlelogin/api', singleapiController.requestLoginOtp);
router.post('/profile/singlelogin/api/verify-otp', singleapiController.verifyLoginOtp);
router.post('/profile/login/verify-password', singleapiController.verifypass);
router.post('/profile/login/fetch-abha', singleapiController.fetchAbha);

export default router;
